/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Matrix */

#ifndef _Included_Matrix
#define _Included_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Matrix
 * Method:    transpose
 * Signature: (LMatrix;)LMatrix;
 */
JNIEXPORT jobject JNICALL Java_Matrix_transpose
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Matrix
 * Method:    is_equal
 * Signature: (LMatrix;)Z
 */
JNIEXPORT jboolean JNICALL Java_Matrix_is_1equal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Matrix
 * Method:    get_element
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_Matrix_get_1element
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Matrix
 * Method:    set_element
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_Matrix_set_1element
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     Matrix
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Matrix_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
