/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Neural */

#ifndef _Included_Neural
#define _Included_Neural
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Neural
 * Method:    feedforward
 * Signature: (LMatrix;)LMatrix;
 */
JNIEXPORT jobject JNICALL Java_Neural_feedforward
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Neural
 * Method:    train
 * Signature: (LMatrix;LMatrix;)V
 */
JNIEXPORT void JNICALL Java_Neural_train
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
